#!/bin/sh
set -e

# Compile the upstream core, if it has been symlinked:
if [ -L ./node_modules/edge-core-js ]; then
  (
    cd ./node_modules/edge-core-js
    npm run prepare
  )
fi

# Compile the CLI:
./node_modules/.bin/rollup -c
chmod +x ./bin/edge-cli

# Run the CLI:
./bin/edge-cli "$@"
